version: "3.9"
   
services:
  db:
    container_name: vaccined_db
    image: postgres:12.0-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nudges
    ports:
      - '5432:5432'

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: vaccined_api
    env_file:
      - api/.api_env
    working_dir: /code/api
    command: bash -c "cron && uvicorn main_api:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nudges
    depends_on:
      - db
    volumes:
      - ./api:/code/api
    ports:
      - "8000:8000"   
      - "8082:8082"
    restart: on-failure

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: vacunados_web
    working_dir: /code/src
    restart: on-failure
    
    command: bash -c "python3 main.py"

    environment:
      DEBUG: 1
    volumes:
      - ./web:/code
    ports:
      - 5000:5000
    depends_on:
      - api
      - db


  etl:
    build:
      context: ./etl
      dockerfile: Dockerfile
    container_name: vacunados_etl
    working_dir: /code/src
    restart: on-failure
    
    command: bash -c "dagit -h 0.0.0.0 -f hell_world.py"

    environment:
      DEBUG: 1
    volumes:
      - ./etl:/code
    ports:
      - 3000:3000
    depends_on:
      - api
      - db


