version: "3.9"
   
services:
  db:
    image: postgres:12.0-alpine

    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nudges
    command: -p 5433
    ports:
      - '5433:5433'

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file:
      - api/.api_env
    working_dir: /code/api
    command: bash -c "cron && uvicorn main_api:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nudges
    depends_on:
      - db
    volumes:
      - ./api:/code/api
    ports:
      - "8000:8000"   
    restart: on-failure

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    working_dir: /code/src
    restart: on-failure
    
    environment:
      DEBUG: 1
    volumes:
      - ./web:/code
    ports:
      - 5000:5000
    depends_on:
      - db
      - api

  dagster-dagit:
    build: ./etl
    ports:
      - 3000:3000

  dagster-daemon:
    build: ./etl
    command: "dagster-daemon run"

  dagster-postgres:
    image: postgres:13.3
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=secret
    volumes:
      - dagster-postgres:/var/lib/postgresql/data
volumes:
  dagster-postgres:
    driver: local

