version: "3.9"
   
services:
  db:
    container_name: vaccined_db
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: vaccined_api
    working_dir: /code/api
    command: bash -c "cron && uvicorn main_api:app --host 0.0.0.0 --port 8000 --reload"
    environment:
      DEBUG: 1
    volumes:
      - ./api:/code/api
    ports:
      - "8000:8000"    # maquina:container
    restart: on-failure

  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: vaccined_web
    working_dir: /code/web
    restart: on-failure
    
    command: bash -c "python3 main_web.py"

    environment:
      DEBUG: 1
    volumes:
      - ./web:/code/web
    ports:
      - "8080:8080"
